#ifndef GUARD_CONSTANTS_BATTLE_EVENTS_H
#define GUARD_CONSTANTS_BATTLE_EVENTS_H

#define BATTLE_EVENT_NONE               0
#define BATTLE_EVENT_STEADY_OFFENSE     1
#define BATTLE_EVENT_STEADY_DEFENSE     2
#define BATTLE_EVENT_STEADY_SPECIAL     3
#define BATTLE_EVENT_STEADY_SPDEF       4
#define BATTLE_EVENT_STEADY_SPEED       5
#define BATTLE_EVENT_STEADY_PRECISION   6
#define BATTLE_EVENT_STEADY_CRIT        7
#define BATTLE_EVENT_POSTURE_OFFENSE    8  
#define BATTLE_EVENT_POSTURE_DEFENSE    9
#define BATTLE_EVENT_POSTURE_SPECIAL    10
#define BATTLE_EVENT_POSTURE_SPDEF      11
#define BATTLE_EVENT_POSTURE_SPEED      12
#define BATTLE_EVENT_POSTURE_PRECISION  13
#define BATTLE_EVENT_POSTURE_CRIT       14
// void of 15
#define BATTLE_EVENT_LAST_PARALYZED     30
#define BATTLE_EVENT_LAST_BURNED        31
#define BATTLE_EVENT_LAST_SLEEP         32
#define BATTLE_EVENT_LAST_FROSTBITE     33
#define BATTLE_EVENT_LAST_BLEED         34
#define BATTLE_EVENT_LAST_POISONED      35
#define BATTLE_EVENT_LAST_TOXIC         36
// void of 24
#define BATTLE_EVENT_STEALTH_ROCK       60
#define BATTLE_EVENT_CREEPING_THORNS    61
#define BATTLE_EVENT_SPIKES             62
// void of 8
#define BATTLE_EVENT_ELECTRIC_SURGE     70
#define BATTLE_EVENT_PSYCHIC_SURGE      71
#define BATTLE_EVENT_GRASSY_SURGE       72
#define BATTLE_EVENT_MISTY_SURGE        73
//void of 7
#define BATTLE_EVENT_RAIN               80
#define BATTLE_EVENT_SUN                81
// void of 19
#define BATTLE_EVENT_RISE_OF_THE_FALLEN 100


#endif // GUARD_CONSTANTS_BATTLE_EVENTS_H