#ifndef GUARD_CONSTANTS_BATTLE_EVENTS_H
#define GUARD_CONSTANTS_BATTLE_EVENTS_H

#define BATTLE_EVENT_NONE 0
#define BATTLE_EVENT_STEALTH_ROCK_START 1
#define BATTLE_EVENT_LAST_PARALYZED 2
#define BATTLE_EVENT_LEADER_1RST_PLUS_FOUR_DEF_BOOST 3
#define BATTLE_EVENT_STEADY_DEFENSE 4

#define BATTLE_EVENTS_COUNT BATTLE_EVENT_STEADY_DEFENSE + 1

#endif // GUARD_CONSTANTS_BATTLE_EVENTS_H