#pragma once

#if USE_GENERATED_MOVES
#include "generated/constants/move_effects.h"
#else

#define MOVE_EFFECT_NONE                   0
#define MOVE_EFFECT_SLEEP                  1
#define MOVE_EFFECT_POISON                 2
#define MOVE_EFFECT_BURN                   3
#define MOVE_EFFECT_FREEZE                 4
#define MOVE_EFFECT_PARALYSIS              5
#define MOVE_EFFECT_TOXIC                  6
#define MOVE_EFFECT_FROSTBITE              7
#define MOVE_EFFECT_BLEED                  8
#define MOVE_EFFECT_CONFUSION              9
#define MOVE_EFFECT_FLINCH                 10
#define MOVE_EFFECT_TRI_ATTACK             11
#define MOVE_EFFECT_UPROAR                 12
#define MOVE_EFFECT_PAYDAY                 13
#define MOVE_EFFECT_CHARGING               14
#define MOVE_EFFECT_WRAP                   15
#define MOVE_EFFECT_INCINERATE 			   16
#define MOVE_EFFECT_ATK_PLUS_1             17
#define MOVE_EFFECT_DEF_PLUS_1             18
#define MOVE_EFFECT_SPD_PLUS_1             19
#define MOVE_EFFECT_SP_ATK_PLUS_1          20
#define MOVE_EFFECT_SP_DEF_PLUS_1          21
#define MOVE_EFFECT_ACC_PLUS_1             22
#define MOVE_EFFECT_EVS_PLUS_1             23
#define MOVE_EFFECT_ATK_MINUS_1            24
#define MOVE_EFFECT_DEF_MINUS_1            25
#define MOVE_EFFECT_SPD_MINUS_1            26
#define MOVE_EFFECT_SP_ATK_MINUS_1         27
#define MOVE_EFFECT_SP_DEF_MINUS_1         28
#define MOVE_EFFECT_ACC_MINUS_1            29
#define MOVE_EFFECT_EVS_MINUS_1            30
#define MOVE_EFFECT_RECHARGE               31
#define MOVE_EFFECT_RAGE                   32
#define MOVE_EFFECT_STEAL_ITEM             33
#define MOVE_EFFECT_PREVENT_ESCAPE         34
#define MOVE_EFFECT_NIGHTMARE              35
#define MOVE_EFFECT_ALL_STATS_UP           36
#define MOVE_EFFECT_RAPIDSPIN              37
#define MOVE_EFFECT_REMOVE_STATUS          38
#define MOVE_EFFECT_ATK_DEF_DOWN           39
#define MOVE_EFFECT_RECOIL_HP_25           40
#define MOVE_EFFECT_ATK_PLUS_2             41
#define MOVE_EFFECT_DEF_PLUS_2             42
#define MOVE_EFFECT_SPD_PLUS_2             43
#define MOVE_EFFECT_SP_ATK_PLUS_2          44
#define MOVE_EFFECT_SP_DEF_PLUS_2          45
#define MOVE_EFFECT_ACC_PLUS_2             46
#define MOVE_EFFECT_EVS_PLUS_2             47
#define MOVE_EFFECT_ATK_MINUS_2            48
#define MOVE_EFFECT_DEF_MINUS_2            49
#define MOVE_EFFECT_SPD_MINUS_2            50
#define MOVE_EFFECT_SP_ATK_MINUS_2         51
#define MOVE_EFFECT_SP_DEF_MINUS_2         52
#define MOVE_EFFECT_ACC_MINUS_2            53
#define MOVE_EFFECT_EVS_MINUS_2            54
#define MOVE_EFFECT_THRASH                 55
#define MOVE_EFFECT_KNOCK_OFF              56
#define MOVE_EFFECT_DEF_SPDEF_DOWN         57
#define MOVE_EFFECT_BURN_UP                58
#define MOVE_EFFECT_CLEAR_SMOG             59
#define MOVE_EFFECT_BUG_BITE               60
#define MOVE_EFFECT_SP_ATK_TWO_DOWN        61
#define MOVE_EFFECT_SMACK_DOWN             62
#define MOVE_EFFECT_FLAME_BURST            63
#define MOVE_EFFECT_FEINT                  64
#define MOVE_EFFECT_SPECTRAL_THIEF         65
#define MOVE_EFFECT_V_CREATE               66
#define MOVE_EFFECT_HAPPY_HOUR             67
#define MOVE_EFFECT_CORE_ENFORCER          68
#define MOVE_EFFECT_THROAT_CHOP            69
#define MOVE_EFFECT_RELIC_SONG             70
#define MOVE_EFFECT_TRAP_BOTH              71
#define MOVE_EFFECT_SPD_PLUS_1_DEF_MINUS_1 72
#define MOVE_EFFECT_ATTRACT                73
#define MOVE_EFFECT_CURSE                  74
#define MOVE_EFFECT_DISABLE                75
#define MOVE_EFFECT_GLAIVE_RUSH            76
#define MOVE_EFFECT_SALT_CURE              77
#define MOVE_EFFECT_ORDER_UP               78
#define MOVE_EFFECT_WATER_PLEDGE           79
#define MOVE_EFFECT_FIRE_PLEDGE            80
#define MOVE_EFFECT_GRASS_PLEDGE           81
#define MOVE_EFFECT_RAINBOW                82
#define MOVE_EFFECT_FIRE_SEA               83
#define MOVE_EFFECT_SWAMP                  84
#define MOVE_EFFECT_SYRUP                  85
#define MOVE_EFFECT_DIRE_CLAW              86
#define MOVE_EFFECT_SMOKESCREEN            87
#define MOVE_EFFECT_FEAR                   88
#define MOVE_EFFECT_YAWN                   89
#define MOVE_EFFECT_PSYCHIC_NOISE          90
#define MOVE_EFFECT_HIGHEST_STAT_EXCEPT_SPEED_PLUS_1 91
#define MOVE_EFFECT_MAKE_IT_RAIN           92
#define MOVE_EFFECT_WYRM_WIND              93
#define MOVE_EFFECT_SCALE_SHOT             94
#define MOVE_EFFECT_DOUBLESLAP             95
#define NUM_MOVE_EFFECTS                   95

#endif
