#ifndef GUARD_CONSTANTS_PARTY_MENU_H
#define GUARD_CONSTANTS_PARTY_MENU_H

#define AILMENT_NONE  0
#define AILMENT_PSN   1
#define AILMENT_PRZ   2
#define AILMENT_SLP   3
#define AILMENT_FRZ   4
#define AILMENT_BRN   5
#define AILMENT_PKRS  6
#define AILMENT_FNT   7
#define AILMENT_FSB   8
#define AILMENT_BLD   9

#define PARTY_CHOOSE_MON        0
#define PARTY_MUST_CHOOSE_MON   1
#define PARTY_CANT_SWITCH       2
#define PARTY_USE_ITEM_ON       3
#define PARTY_ABILITY_PREVENTS  4
#define PARTY_GIVE_ITEM         5

#define TUTOR_MOVE_RAGE_POWDER	    0
#define TUTOR_MOVE_SPIDER_WEB	    1
#define TUTOR_MOVE_BUG_BITE	        2
#define TUTOR_MOVE_STRING_SHOT	    3
#define TUTOR_MOVE_THIEF	        4
#define TUTOR_MOVE_PURSUIT          5
#define TUTOR_MOVE_FOUL_PLAY	    6
#define TUTOR_MOVE_BLOOD_SHOT	    7
#define TUTOR_MOVE_TORMENT	        8
#define TUTOR_MOVE_TOPSY_TURSY	    9
#define TUTOR_MOVE_KNOCK_OFF	    10
#define TUTOR_MOVE_DRAGON_TAIL	    11
#define TUTOR_MOVE_BREAKING_SWIPE	12
#define TUTOR_MOVE_DRAGON_CHEER	    13
#define TUTOR_MOVE_THUNDER_WAVE	    14
#define TUTOR_MOVE_FLASH	        15
#define TUTOR_MOVE_ELECTROWEB	    16
#define TUTOR_MOVE_MAGNET_RISE	    17
#define TUTOR_MOVE_CHARGE_BEAM	    18
#define TUTOR_MOVE_ELECTRIC_TERRAIN	19
#define TUTOR_MOVE_SWEET_KISS	    20
#define TUTOR_MOVE_FLORAL_HEALING	21
#define TUTOR_MOVE_CHARM	        22
#define TUTOR_MOVE_BABY_DOLL_EYES	23
#define TUTOR_MOVE_MISTY_TERRAIN	24
#define TUTOR_MOVE_FORCE_PALM	    25
#define TUTOR_MOVE_LOW_KICK	        26
#define TUTOR_MOVE_SEISMIC_TOSS	    27
#define TUTOR_MOVE_POWER_UP_PUNCH	28
#define TUTOR_MOVE_FOCUS_PUNCH	    29
#define TUTOR_MOVE_COUNTER	        30
#define TUTOR_MOVE_MACH_PUNCH	    31
#define TUTOR_MOVE_CIRCLE_THROW	32
#define TUTOR_MOVE_WILL_O_WISP	    33
#define TUTOR_MOVE_FLAME_CHARGE	    34
#define TUTOR_MOVE_FIRE_SPIN	    35
#define TUTOR_MOVE_HEAT_CRASH	    36
#define TUTOR_MOVE_ROOST	        37
#define TUTOR_MOVE_FLY	            38
#define TUTOR_MOVE_PLUCK	        39
#define TUTOR_MOVE_DEFOG	        40
#define TUTOR_MOVE_ACROBATICS	    41
#define TUTOR_MOVE_WHIRLWIND	    42
#define TUTOR_MOVE_SKY_DROP	        43
#define TUTOR_MOVE_TAILWIND	        44
#define TUTOR_MOVE_SPITE	        45
#define TUTOR_MOVE_LICK             46
#define TUTOR_MOVE_HEX	            47
#define TUTOR_MOVE_CURSE	        48
#define TUTOR_MOVE_NIGHT_SHADE	    49
#define TUTOR_MOVE_GRUDGE	        50
#define TUTOR_MOVE_ABSORB	        51
#define TUTOR_MOVE_WORRY_SEED	    52
#define TUTOR_MOVE_AROMATHERAPY	    53
#define TUTOR_MOVE_LEECH_SEED	    54
#define TUTOR_MOVE_COTTON_SPORE	    55
#define TUTOR_MOVE_INGRAIN	        55
#define TUTOR_MOVE_LEAF_TORNADO	    56
#define TUTOR_MOVE_GRASSY_TERRAIN   57
#define TUTOR_MOVE_CREEPING_THORNS	58
#define TUTOR_MOVE_ROTOTILLER	    59
#define TUTOR_MOVE_SAND_TOMB	    60
#define TUTOR_MOVE_SPIKES	        61
#define TUTOR_MOVE_DIG	            62
#define TUTOR_MOVE_AURORA_BEAM	    63
#define TUTOR_MOVE_FLASH_FREEZE	    64
#define TUTOR_MOVE_HAZE	            65
#define TUTOR_MOVE_MIST	            66
#define TUTOR_MOVE_SUPERSONIC	    67
#define TUTOR_MOVE_FEINT	        68
#define TUTOR_MOVE_COVET	        69
#define TUTOR_MOVE_BRAVADO	        70
#define TUTOR_MOVE_LASER_FOCUS	    71
#define TUTOR_MOVE_COPYCAT	        72
#define TUTOR_MOVE_SLEEP_TALK	    73
#define TUTOR_MOVE_TEARFUL_LOOK	    74
#define TUTOR_MOVE_REFRESH	        75
#define TUTOR_MOVE_HELPING_HAND	    76
#define TUTOR_MOVE_RETALIATE	    77
#define TUTOR_MOVE_FALSE_SWIPE	    78
#define TUTOR_MOVE_ENDURE	        79
#define TUTOR_MOVE_SAFEGUARD	    80
#define TUTOR_MOVE_RAPID_SPIN	    81
#define TUTOR_MOVE_FACADE	        82
#define TUTOR_MOVE_WEATHER_BALL	    83
#define TUTOR_MOVE_WORK_UP	        84
#define TUTOR_MOVE_SPOTLIGHT	    85
#define TUTOR_MOVE_POISON_TAIL	    86
#define TUTOR_MOVE_TOXIC_SPIKES	    87
#define TUTOR_MOVE_CLEAR_SMOG	    88
#define TUTOR_MOVE_CORROSIVE_GAS	89
#define TUTOR_MOVE_TOXIC	        90
#define TUTOR_MOVE_GASTRO_ACID	    91
#define TUTOR_MOVE_ACID_ARMOR	    92
#define TUTOR_MOVE_VENOM_DRENCH	    93
#define TUTOR_MOVE_PSYBEAM	        94
#define TUTOR_MOVE_MIRACLE_EYE	    95
#define TUTOR_MOVE_REST	            96
#define TUTOR_MOVE_TRICK_ROOM	    97
#define TUTOR_MOVE_PSYCHIC_NOISE	98
#define TUTOR_MOVE_REFLECT	        99
#define TUTOR_MOVE_LIGHT_SCREEN	    100
#define TUTOR_MOVE_TRICK	        101
#define TUTOR_MOVE_MIRROR_COAT	    102
#define TUTOR_MOVE_SKILL_SWAP	    103
#define TUTOR_MOVE_HEAL_BLOCK	    104
#define TUTOR_MOVE_EERIE_SPELL	    105
#define TUTOR_MOVE_PSYCHIC_TERRAIN	106
#define TUTOR_MOVE_STEALTH_ROCK	    107
#define TUTOR_MOVE_WIDE_GUARD	    108
#define TUTOR_MOVE_IRON_DEFENSE	    109
#define TUTOR_MOVE_MIRROR_SHOT	    110
#define TUTOR_MOVE_HEAVY_SLAM	    111
#define TUTOR_MOVE_HARD_PRESS	    112
#define TUTOR_MOVE_METAL_SOUND	    113
#define TUTOR_MOVE_WHIRLPOOL	    114
#define TUTOR_MOVE_SOAK	            115
#define TUTOR_MOVE_DIVE	            116
#define TUTOR_MOVE_AQUA_RING	    117
#define TUTOR_MOVE_LIFE_DEW	        118
/*
#define TUTOR_MOVE_GRASSY_TERRAIN	119
#define TUTOR_MOVE_ELECTRIC_TERRAIN	120
#define TUTOR_MOVE_MISTY_TERRAIN	121
#define TUTOR_MOVE_PSYCHIC_TERRAIN	122
#define TUTOR_MOVE_AIR_SLASH	    123
#define TUTOR_MOVE_METEOR_MASH	    124
#define TUTOR_MOVE_AURORA_BEAM	    125
#define TUTOR_MOVE_QUIVER_DANCE	    126
#define TUTOR_MOVE_EXPANDING_FORCE  127
#define TUTOR_MOVE_RISING_VOLTAGE   128
#define TUTOR_MOVE_MISTY_EXPLOSION  129
#define TUTOR_MOVE_GRASSY_GLIDE     130
#define TUTOR_MOVE_TERRAIN_PULSE    131
#define TUTOR_MOVE_SCALE_SHOT       132
#define TUTOR_MOVE_METEOR_BEAM      133
#define TUTOR_MOVE_POLTERGEIST      134
#define TUTOR_MOVE_FLIP_TURN        135
#define TUTOR_MOVE_TRIPLE_AXEL      136
#define TUTOR_MOVE_DUAL_WINGBEAT    137
#define TUTOR_MOVE_SCORCHING_SANDS  138
#define TUTOR_MOVE_SKITTER_SMACK    139
#define TUTOR_MOVE_COACHING         140
#define TUTOR_MOVE_BODY_PRESS       141
#define TUTOR_MOVE_FOCUS_ENERGY     142
#define TUTOR_MOVE_SPIKES           143
#define TUTOR_MOVE_HIGH_HORSEPOWER  144
#define TUTOR_MOVE_STOMPING_TANTRUM 145
#define TUTOR_MOVE_INFESTATION      146
#define TUTOR_MOVE_POWER_UP_PUNCH   147
#define TUTOR_MOVE_AGILITY          148
#define TUTOR_MOVE_TELEPORT         149 */

#define PARTY_LAYOUT_SINGLE          0
#define PARTY_LAYOUT_DOUBLE          1
#define PARTY_LAYOUT_MULTI           2
#define PARTY_LAYOUT_MULTI_SHOWCASE  3  // The layout during the screen that appears just before a multi battle
#define PARTY_LAYOUT_COUNT           4
#define KEEP_PARTY_LAYOUT            0xFF

#define PARTY_MENU_TYPE_FIELD                     0 
#define PARTY_MENU_TYPE_IN_BATTLE                 1 
#define PARTY_MENU_TYPE_CONTEST                   2 
#define PARTY_MENU_TYPE_CHOOSE_MON                3 
#define PARTY_MENU_TYPE_CHOOSE_HALF               4  // multi battles, eReader battles, and some battle facilities
#define PARTY_MENU_TYPE_MULTI_SHOWCASE            5
#define PARTY_MENU_TYPE_DAYCARE                   6 
#define PARTY_MENU_TYPE_MOVE_RELEARNER            7 
#define PARTY_MENU_TYPE_UNION_ROOM_REGISTER       8  // trading board
#define PARTY_MENU_TYPE_UNION_ROOM_TRADE          9  // trading board
#define PARTY_MENU_TYPE_SPIN_TRADE                10 // Unused beta for Gen IV's Spin Trade
#define PARTY_MENU_TYPE_MINIGAME                  11
#define PARTY_MENU_TYPE_STORE_PYRAMID_HELD_ITEMS  12

#define PARTY_ACTION_CHOOSE_MON         0
#define PARTY_ACTION_SEND_OUT           1
#define PARTY_ACTION_CANT_SWITCH        2
#define PARTY_ACTION_USE_ITEM           3
#define PARTY_ACTION_ABILITY_PREVENTS   4
#define PARTY_ACTION_GIVE_ITEM          5  
#define PARTY_ACTION_GIVE_PC_ITEM       6   // Unused. Not possible to give non-mail items directly from PC
#define PARTY_ACTION_GIVE_MAILBOX_MAIL  7
#define PARTY_ACTION_SWITCH             8
#define PARTY_ACTION_SWITCHING          9
#define PARTY_ACTION_SOFTBOILED         10
#define PARTY_ACTION_CHOOSE_AND_CLOSE   11
#define PARTY_ACTION_MOVE_TUTOR         12
#define PARTY_ACTION_MINIGAME           13
#define PARTY_ACTION_REUSABLE_ITEM      14  // Unused. The only reusable items are handled separately
#define PARTY_ACTION_CHOOSE_FAINTED_MON 15

// IDs for DisplayPartyMenuStdMessage, to display the message at the bottom of the party menu
#define PARTY_MSG_CHOOSE_MON                0
#define PARTY_MSG_CHOOSE_MON_OR_CANCEL      1
#define PARTY_MSG_CHOOSE_MON_AND_CONFIRM    2
#define PARTY_MSG_MOVE_TO_WHERE             3 
#define PARTY_MSG_TEACH_WHICH_MON           4
#define PARTY_MSG_USE_ON_WHICH_MON          5
#define PARTY_MSG_GIVE_TO_WHICH_MON         6
#define PARTY_MSG_NOTHING_TO_CUT            7
#define PARTY_MSG_CANT_SURF_HERE            8
#define PARTY_MSG_ALREADY_SURFING           9
#define PARTY_MSG_CURRENT_TOO_FAST          10
#define PARTY_MSG_ENJOY_CYCLING             11
#define PARTY_MSG_ALREADY_IN_USE            12
#define PARTY_MSG_CANT_USE_HERE             13
#define PARTY_MSG_NO_MON_FOR_BATTLE         14
#define PARTY_MSG_CHOOSE_MON_2              15
#define PARTY_MSG_NOT_ENOUGH_HP             16
#define PARTY_MSG_X_MONS_ARE_NEEDED         17
#define PARTY_MSG_MONS_CANT_BE_SAME         18
#define PARTY_MSG_NO_SAME_HOLD_ITEMS        19
#define PARTY_MSG_UNUSED                    20
#define PARTY_MSG_DO_WHAT_WITH_MON          21
#define PARTY_MSG_RESTORE_WHICH_MOVE        22
#define PARTY_MSG_BOOST_PP_WHICH_MOVE       23
#define PARTY_MSG_DO_WHAT_WITH_ITEM         24
#define PARTY_MSG_DO_WHAT_WITH_MAIL         25
#define PARTY_MSG_ALREADY_HOLDING_ONE       26
#define PARTY_MSG_MOVE_ITEM_WHERE           27
#define PARTY_MSG_CHOSE_LEVEL               28
#define PARTY_MSG_NONE                      127

// IDs for DisplayPartyPokemonDescriptionText, to display a message in the party pokemon's box
#define PARTYBOX_DESC_NO_USE      0
#define PARTYBOX_DESC_ABLE_3      1
#define PARTYBOX_DESC_FIRST       2
#define PARTYBOX_DESC_SECOND      3
#define PARTYBOX_DESC_THIRD       4
#define PARTYBOX_DESC_FOURTH      5
#define PARTYBOX_DESC_ABLE        6
#define PARTYBOX_DESC_NOT_ABLE    7
#define PARTYBOX_DESC_ABLE_2      8
#define PARTYBOX_DESC_NOT_ABLE_2  9
#define PARTYBOX_DESC_LEARNED     10
#define PARTYBOX_DESC_HAVE        11
#define PARTYBOX_DESC_DONT_HAVE   12

#define SELECTWINDOW_ACTIONS  0
#define SELECTWINDOW_ITEM     1
#define SELECTWINDOW_MAIL     2
#define SELECTWINDOW_MOVES    3
#define SELECTWINDOW_LEVEL_UP 4

#endif // GUARD_CONSTANTS_PARTY_MENU_H
