package er

import er.data.*
import er.defines.AbilitiesEnumGenerator
import er.defines.MovesEnumGenerator
import er.defines.SpeciesEnumGenerator
import er.gfx.CoordsGenerator
import er.gfx.IconGenerator
import er.gfx.ImageGenerator
import er.gfx.PaletteGenerator
import er.move.MoveDescriptionGenerator
import er.move.MoveNameGenerator
import er.text.ArticlesGenerator
import java.io.File
import java.io.OutputStreamWriter

interface Generator {
    fun generate(writer: OutputStreamWriter)
}

object FileGenerator {
    val Generator.header get() = """
        |// This file is autogenerated by ${this::class.qualifiedName} via FileGenerator.kt. Do not manually modify it.
        |
    """.trimMargin()

    const val IND = "    "

    val GENERATORS = mapOf(
        "abilities" to AbilitiesEnumGenerator,
        "moves" to MovesEnumGenerator,
        "species" to SpeciesEnumGenerator,
        "basestats" to BaseStatsGenerator,
        "evos" to EvolutionsGenerator,
        "speciesnames" to SpeciesNameGenerator,
        "tutorlearnsets" to TutorLearnsetGenerator,
        "leveluplearnsets" to LevelUpLearnsetGenerator,
        "forms" to FormSpeciesTableGenerator,
        "icons" to IconGenerator,
        "monpics" to ImageGenerator,
        "coords" to CoordsGenerator,
        "monpals" to PaletteGenerator,
        "helparticles" to ArticlesGenerator,
        "movenames" to MoveNameGenerator,
        "movedescriptions" to MoveDescriptionGenerator,
    )

    @JvmStatic
    fun main(args: Array<String>) {
        val (type, filepath) = args
        try {
            val file = File(filepath)
            file.parentFile.mkdirs()
            val generator = GENERATORS[type] ?: error("No generator $type for file $filepath")
            file.writer().use { generator.generate(it) }
        } catch (e: Exception) {
            throw Exception("Failed processing $type generating file $filepath", e)
        }
    }
}