package er

import er.ability.AbilityTextGenerator
import er.data.*
import er.defines.*
import er.gfx.CoordsGenerator
import er.gfx.IconGenerator
import er.gfx.ImageGenerator
import er.gfx.PaletteGenerator
import er.move.BattleMovesGenerator
import er.move.MoveDescriptionGenerator
import er.move.MoveNameGenerator
import er.text.ArticlesGenerator
import java.io.File
import java.io.OutputStreamWriter

interface Generator {
    fun generate(writer: OutputStreamWriter)
}

object FileGenerator {
    private val Generator.header
        get() = """
        |#pragma once
        |// This file is autogenerated by ${this::class.qualifiedName} via FileGenerator.kt. Do not manually modify it.
        |
    """.trimMargin()

    const val IND = "    "

    private val GENERATORS = mapOf(
        "abilities" to AbilitiesEnumGenerator,
        "moves" to MovesEnumGenerator,
        "species" to SpeciesEnumGenerator,
        "basestats" to BaseStatsGenerator,
        "evos" to EvolutionsGenerator,
        "speciesnames" to SpeciesNameGenerator,
        "tutorlearnsets" to TutorLearnsetGenerator,
        "leveluplearnsets" to LevelUpLearnsetGenerator,
        "forms" to FormSpeciesTableGenerator,
        "icons" to IconGenerator,
        "monpics" to ImageGenerator,
        "coords" to CoordsGenerator,
        "monpals" to PaletteGenerator,
        "helparticles" to ArticlesGenerator,
        "movenames" to MoveNameGenerator,
        "movedescriptions" to MoveDescriptionGenerator,
        "movebehaviors" to MoveBehaviorGenerator,
        "moveeffects" to MoveEffectGenerator,
        "battlemoves" to BattleMovesGenerator,
        "reversemegamap" to ReverseMegaMappingGenerator,
        "abilitytext" to AbilityTextGenerator,
        "pokedexentries" to PokedexEntriesGenerator,
        "pokedexorders" to PokedexOrdersGenerator,
        "pokedexnumbers" to PokedexNumbersMapGenerator,
        "randomizerbanned" to RandomizerBannedGenerator,
        "longnames" to SpeciesLongNameGenerator,
        "speciesanims" to SpeciesAnimationGenerator,
    )

    @JvmStatic
    fun main(args: Array<String>) {
        val (type, filepath) = args
        try {
            val file = File(filepath)
            file.parentFile.mkdirs()
            val generator = GENERATORS[type] ?: error("No generator $type for file $filepath")
            file.writer().use {
                it.appendLine(generator.header)
                try {
                    generator.generate(it)
                } catch (e: Exception) {
                    it.appendLine(e.stackTraceToString())
                    throw e
                }
            }
        } catch (e: Exception) {
            throw Exception("Failed processing $type generating file $filepath", e)
        }
    }
}