// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ScriptConditions.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package er;

@kotlin.jvm.JvmName("-initializescriptCondition")
public inline fun scriptCondition(block: er.ScriptConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition =
  er.ScriptConditionKt.Dsl._create(er.ScriptConditions.ScriptCondition.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `er.ScriptCondition`
 */
public object ScriptConditionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: er.ScriptConditions.ScriptCondition.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: er.ScriptConditions.ScriptCondition.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): er.ScriptConditions.ScriptCondition = _builder.build()

    /**
     * `.er.ScriptCondition.WeatherCondition weather = 1;`
     */
    public var weather: er.ScriptConditions.ScriptCondition.WeatherCondition
      @JvmName("getWeather")
      get() = _builder.weather
      @JvmName("setWeather")
      set(value) {
        _builder.weather = value
      }
    /**
     * `.er.ScriptCondition.WeatherCondition weather = 1;`
     */
    public fun clearWeather() {
      _builder.clearWeather()
    }
    /**
     * `.er.ScriptCondition.WeatherCondition weather = 1;`
     * @return Whether the weather field is set.
     */
    public fun hasWeather(): kotlin.Boolean {
      return _builder.hasWeather()
    }

    /**
     * `.er.ScriptCondition.Damaged damaged = 2;`
     */
    public var damaged: er.ScriptConditions.ScriptCondition.Damaged
      @JvmName("getDamaged")
      get() = _builder.damaged
      @JvmName("setDamaged")
      set(value) {
        _builder.damaged = value
      }
    /**
     * `.er.ScriptCondition.Damaged damaged = 2;`
     */
    public fun clearDamaged() {
      _builder.clearDamaged()
    }
    /**
     * `.er.ScriptCondition.Damaged damaged = 2;`
     * @return Whether the damaged field is set.
     */
    public fun hasDamaged(): kotlin.Boolean {
      return _builder.hasDamaged()
    }

    /**
     * `.er.ScriptCondition.StatusCondition status = 3;`
     */
    public var status: er.ScriptConditions.ScriptCondition.StatusCondition
      @JvmName("getStatus")
      get() = _builder.status
      @JvmName("setStatus")
      set(value) {
        _builder.status = value
      }
    /**
     * `.er.ScriptCondition.StatusCondition status = 3;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
    /**
     * `.er.ScriptCondition.StatusCondition status = 3;`
     * @return Whether the status field is set.
     */
    public fun hasStatus(): kotlin.Boolean {
      return _builder.hasStatus()
    }

    /**
     * `.er.ScriptCondition.Switching switching = 4;`
     */
    public var switching: er.ScriptConditions.ScriptCondition.Switching
      @JvmName("getSwitching")
      get() = _builder.switching
      @JvmName("setSwitching")
      set(value) {
        _builder.switching = value
      }
    /**
     * `.er.ScriptCondition.Switching switching = 4;`
     */
    public fun clearSwitching() {
      _builder.clearSwitching()
    }
    /**
     * `.er.ScriptCondition.Switching switching = 4;`
     * @return Whether the switching field is set.
     */
    public fun hasSwitching(): kotlin.Boolean {
      return _builder.hasSwitching()
    }

    /**
     * `.er.ScriptCondition.ActsAfter acts_after = 5;`
     */
    public var actsAfter: er.ScriptConditions.ScriptCondition.ActsAfter
      @JvmName("getActsAfter")
      get() = _builder.actsAfter
      @JvmName("setActsAfter")
      set(value) {
        _builder.actsAfter = value
      }
    /**
     * `.er.ScriptCondition.ActsAfter acts_after = 5;`
     */
    public fun clearActsAfter() {
      _builder.clearActsAfter()
    }
    /**
     * `.er.ScriptCondition.ActsAfter acts_after = 5;`
     * @return Whether the actsAfter field is set.
     */
    public fun hasActsAfter(): kotlin.Boolean {
      return _builder.hasActsAfter()
    }

    /**
     * `.er.ScriptCondition.TerrainCondition terrain = 6;`
     */
    public var terrain: er.ScriptConditions.ScriptCondition.TerrainCondition
      @JvmName("getTerrain")
      get() = _builder.terrain
      @JvmName("setTerrain")
      set(value) {
        _builder.terrain = value
      }
    /**
     * `.er.ScriptCondition.TerrainCondition terrain = 6;`
     */
    public fun clearTerrain() {
      _builder.clearTerrain()
    }
    /**
     * `.er.ScriptCondition.TerrainCondition terrain = 6;`
     * @return Whether the terrain field is set.
     */
    public fun hasTerrain(): kotlin.Boolean {
      return _builder.hasTerrain()
    }

    /**
     * `.er.ScriptCondition.FieldEffectCondition field_effect = 7;`
     */
    public var fieldEffect: er.ScriptConditions.ScriptCondition.FieldEffectCondition
      @JvmName("getFieldEffect")
      get() = _builder.fieldEffect
      @JvmName("setFieldEffect")
      set(value) {
        _builder.fieldEffect = value
      }
    /**
     * `.er.ScriptCondition.FieldEffectCondition field_effect = 7;`
     */
    public fun clearFieldEffect() {
      _builder.clearFieldEffect()
    }
    /**
     * `.er.ScriptCondition.FieldEffectCondition field_effect = 7;`
     * @return Whether the fieldEffect field is set.
     */
    public fun hasFieldEffect(): kotlin.Boolean {
      return _builder.hasFieldEffect()
    }

    /**
     * `.er.ScriptCondition.AbilityCondition ability = 8;`
     */
    public var ability: er.ScriptConditions.ScriptCondition.AbilityCondition
      @JvmName("getAbility")
      get() = _builder.ability
      @JvmName("setAbility")
      set(value) {
        _builder.ability = value
      }
    /**
     * `.er.ScriptCondition.AbilityCondition ability = 8;`
     */
    public fun clearAbility() {
      _builder.clearAbility()
    }
    /**
     * `.er.ScriptCondition.AbilityCondition ability = 8;`
     * @return Whether the ability field is set.
     */
    public fun hasAbility(): kotlin.Boolean {
      return _builder.hasAbility()
    }

    /**
     * `.er.ScriptCondition.Hp hp = 9;`
     */
    public var hp: er.ScriptConditions.ScriptCondition.Hp
      @JvmName("getHp")
      get() = _builder.hp
      @JvmName("setHp")
      set(value) {
        _builder.hp = value
      }
    /**
     * `.er.ScriptCondition.Hp hp = 9;`
     */
    public fun clearHp() {
      _builder.clearHp()
    }
    /**
     * `.er.ScriptCondition.Hp hp = 9;`
     * @return Whether the hp field is set.
     */
    public fun hasHp(): kotlin.Boolean {
      return _builder.hasHp()
    }

    /**
     * `.er.ScriptCondition.RecentFainted recent_fainted = 10;`
     */
    public var recentFainted: er.ScriptConditions.ScriptCondition.RecentFainted
      @JvmName("getRecentFainted")
      get() = _builder.recentFainted
      @JvmName("setRecentFainted")
      set(value) {
        _builder.recentFainted = value
      }
    /**
     * `.er.ScriptCondition.RecentFainted recent_fainted = 10;`
     */
    public fun clearRecentFainted() {
      _builder.clearRecentFainted()
    }
    /**
     * `.er.ScriptCondition.RecentFainted recent_fainted = 10;`
     * @return Whether the recentFainted field is set.
     */
    public fun hasRecentFainted(): kotlin.Boolean {
      return _builder.hasRecentFainted()
    }

    /**
     * `bool custom = 11;`
     */
    public var custom: kotlin.Boolean
      @JvmName("getCustom")
      get() = _builder.custom
      @JvmName("setCustom")
      set(value) {
        _builder.custom = value
      }
    /**
     * `bool custom = 11;`
     */
    public fun clearCustom() {
      _builder.clearCustom()
    }
    /**
     * `bool custom = 11;`
     * @return Whether the custom field is set.
     */
    public fun hasCustom(): kotlin.Boolean {
      return _builder.hasCustom()
    }

    /**
     * `.er.ScriptCondition.SpeciesCondition species = 12;`
     */
    public var species: er.ScriptConditions.ScriptCondition.SpeciesCondition
      @JvmName("getSpecies")
      get() = _builder.species
      @JvmName("setSpecies")
      set(value) {
        _builder.species = value
      }
    /**
     * `.er.ScriptCondition.SpeciesCondition species = 12;`
     */
    public fun clearSpecies() {
      _builder.clearSpecies()
    }
    /**
     * `.er.ScriptCondition.SpeciesCondition species = 12;`
     * @return Whether the species field is set.
     */
    public fun hasSpecies(): kotlin.Boolean {
      return _builder.hasSpecies()
    }

    /**
     * `.er.ScriptCondition.ItemCondition item = 13;`
     */
    public var item: er.ScriptConditions.ScriptCondition.ItemCondition
      @JvmName("getItem")
      get() = _builder.item
      @JvmName("setItem")
      set(value) {
        _builder.item = value
      }
    /**
     * `.er.ScriptCondition.ItemCondition item = 13;`
     */
    public fun clearItem() {
      _builder.clearItem()
    }
    /**
     * `.er.ScriptCondition.ItemCondition item = 13;`
     * @return Whether the item field is set.
     */
    public fun hasItem(): kotlin.Boolean {
      return _builder.hasItem()
    }
    public val conditionCase: er.ScriptConditions.ScriptCondition.ConditionCase
    @kotlin.jvm.JvmName("getConditionCase")
      get() = _builder.getConditionCase()

    public fun clearCondition() {
      _builder.clearCondition()
    }
  }
  @kotlin.jvm.JvmName("-initializeweatherCondition")
  public inline fun weatherCondition(block: er.ScriptConditionKt.WeatherConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.WeatherCondition =
    er.ScriptConditionKt.WeatherConditionKt.Dsl._create(er.ScriptConditions.ScriptCondition.WeatherCondition.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `er.ScriptCondition.WeatherCondition`
   */
  public object WeatherConditionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: er.ScriptConditions.ScriptCondition.WeatherCondition.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: er.ScriptConditions.ScriptCondition.WeatherCondition.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): er.ScriptConditions.ScriptCondition.WeatherCondition = _builder.build()

      /**
       * `.er.Weather weather = 1;`
       */
      public var weather: er.ScriptConditions.Weather
        @JvmName("getWeather")
        get() = _builder.weather
        @JvmName("setWeather")
        set(value) {
          _builder.weather = value
        }
      public var weatherValue: kotlin.Int
        @JvmName("getWeatherValue")
        get() = _builder.weatherValue
        @JvmName("setWeatherValue")
        set(value) {
          _builder.weatherValue = value
        }
      /**
       * `.er.Weather weather = 1;`
       */
      public fun clearWeather() {
        _builder.clearWeather()
      }

      /**
       * `.er.Battler battler = 2;`
       */
      public var battler: er.ScriptConditions.Battler
        @JvmName("getBattler")
        get() = _builder.battler
        @JvmName("setBattler")
        set(value) {
          _builder.battler = value
        }
      public var battlerValue: kotlin.Int
        @JvmName("getBattlerValue")
        get() = _builder.battlerValue
        @JvmName("setBattlerValue")
        set(value) {
          _builder.battlerValue = value
        }
      /**
       * `.er.Battler battler = 2;`
       */
      public fun clearBattler() {
        _builder.clearBattler()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializedamaged")
  public inline fun damaged(block: er.ScriptConditionKt.DamagedKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.Damaged =
    er.ScriptConditionKt.DamagedKt.Dsl._create(er.ScriptConditions.ScriptCondition.Damaged.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `er.ScriptCondition.Damaged`
   */
  public object DamagedKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: er.ScriptConditions.ScriptCondition.Damaged.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: er.ScriptConditions.ScriptCondition.Damaged.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): er.ScriptConditions.ScriptCondition.Damaged = _builder.build()

      /**
       * `.er.Battler battler = 1;`
       */
      public var battler: er.ScriptConditions.Battler
        @JvmName("getBattler")
        get() = _builder.battler
        @JvmName("setBattler")
        set(value) {
          _builder.battler = value
        }
      public var battlerValue: kotlin.Int
        @JvmName("getBattlerValue")
        get() = _builder.battlerValue
        @JvmName("setBattlerValue")
        set(value) {
          _builder.battlerValue = value
        }
      /**
       * `.er.Battler battler = 1;`
       */
      public fun clearBattler() {
        _builder.clearBattler()
      }

      /**
       * `.er.Battler by = 2;`
       */
      public var by: er.ScriptConditions.Battler
        @JvmName("getBy")
        get() = _builder.by
        @JvmName("setBy")
        set(value) {
          _builder.by = value
        }
      public var byValue: kotlin.Int
        @JvmName("getByValue")
        get() = _builder.byValue
        @JvmName("setByValue")
        set(value) {
          _builder.byValue = value
        }
      /**
       * `.er.Battler by = 2;`
       */
      public fun clearBy() {
        _builder.clearBy()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializestatusCondition")
  public inline fun statusCondition(block: er.ScriptConditionKt.StatusConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.StatusCondition =
    er.ScriptConditionKt.StatusConditionKt.Dsl._create(er.ScriptConditions.ScriptCondition.StatusCondition.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `er.ScriptCondition.StatusCondition`
   */
  public object StatusConditionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: er.ScriptConditions.ScriptCondition.StatusCondition.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: er.ScriptConditions.ScriptCondition.StatusCondition.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): er.ScriptConditions.ScriptCondition.StatusCondition = _builder.build()

      /**
       * `.er.Status status = 1;`
       */
      public var status: er.ScriptConditions.Status
        @JvmName("getStatus")
        get() = _builder.status
        @JvmName("setStatus")
        set(value) {
          _builder.status = value
        }
      public var statusValue: kotlin.Int
        @JvmName("getStatusValue")
        get() = _builder.statusValue
        @JvmName("setStatusValue")
        set(value) {
          _builder.statusValue = value
        }
      /**
       * `.er.Status status = 1;`
       */
      public fun clearStatus() {
        _builder.clearStatus()
      }

      /**
       * `.er.Battler battler = 2;`
       */
      public var battler: er.ScriptConditions.Battler
        @JvmName("getBattler")
        get() = _builder.battler
        @JvmName("setBattler")
        set(value) {
          _builder.battler = value
        }
      public var battlerValue: kotlin.Int
        @JvmName("getBattlerValue")
        get() = _builder.battlerValue
        @JvmName("setBattlerValue")
        set(value) {
          _builder.battlerValue = value
        }
      /**
       * `.er.Battler battler = 2;`
       */
      public fun clearBattler() {
        _builder.clearBattler()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializeswitching")
  public inline fun switching(block: er.ScriptConditionKt.SwitchingKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.Switching =
    er.ScriptConditionKt.SwitchingKt.Dsl._create(er.ScriptConditions.ScriptCondition.Switching.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `er.ScriptCondition.Switching`
   */
  public object SwitchingKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: er.ScriptConditions.ScriptCondition.Switching.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: er.ScriptConditions.ScriptCondition.Switching.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): er.ScriptConditions.ScriptCondition.Switching = _builder.build()

      /**
       * `.er.Battler battler = 1;`
       */
      public var battler: er.ScriptConditions.Battler
        @JvmName("getBattler")
        get() = _builder.battler
        @JvmName("setBattler")
        set(value) {
          _builder.battler = value
        }
      public var battlerValue: kotlin.Int
        @JvmName("getBattlerValue")
        get() = _builder.battlerValue
        @JvmName("setBattlerValue")
        set(value) {
          _builder.battlerValue = value
        }
      /**
       * `.er.Battler battler = 1;`
       */
      public fun clearBattler() {
        _builder.clearBattler()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializeactsAfter")
  public inline fun actsAfter(block: er.ScriptConditionKt.ActsAfterKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.ActsAfter =
    er.ScriptConditionKt.ActsAfterKt.Dsl._create(er.ScriptConditions.ScriptCondition.ActsAfter.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `er.ScriptCondition.ActsAfter`
   */
  public object ActsAfterKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: er.ScriptConditions.ScriptCondition.ActsAfter.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: er.ScriptConditions.ScriptCondition.ActsAfter.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): er.ScriptConditions.ScriptCondition.ActsAfter = _builder.build()

      /**
       * `.er.Battler before = 1;`
       */
      public var before: er.ScriptConditions.Battler
        @JvmName("getBefore")
        get() = _builder.before
        @JvmName("setBefore")
        set(value) {
          _builder.before = value
        }
      public var beforeValue: kotlin.Int
        @JvmName("getBeforeValue")
        get() = _builder.beforeValue
        @JvmName("setBeforeValue")
        set(value) {
          _builder.beforeValue = value
        }
      /**
       * `.er.Battler before = 1;`
       */
      public fun clearBefore() {
        _builder.clearBefore()
      }

      /**
       * `.er.Battler after = 2;`
       */
      public var after: er.ScriptConditions.Battler
        @JvmName("getAfter")
        get() = _builder.after
        @JvmName("setAfter")
        set(value) {
          _builder.after = value
        }
      public var afterValue: kotlin.Int
        @JvmName("getAfterValue")
        get() = _builder.afterValue
        @JvmName("setAfterValue")
        set(value) {
          _builder.afterValue = value
        }
      /**
       * `.er.Battler after = 2;`
       */
      public fun clearAfter() {
        _builder.clearAfter()
      }

      /**
       * `bool fail_if_switching = 3;`
       */
      public var failIfSwitching: kotlin.Boolean
        @JvmName("getFailIfSwitching")
        get() = _builder.failIfSwitching
        @JvmName("setFailIfSwitching")
        set(value) {
          _builder.failIfSwitching = value
        }
      /**
       * `bool fail_if_switching = 3;`
       */
      public fun clearFailIfSwitching() {
        _builder.clearFailIfSwitching()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializeterrainCondition")
  public inline fun terrainCondition(block: er.ScriptConditionKt.TerrainConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.TerrainCondition =
    er.ScriptConditionKt.TerrainConditionKt.Dsl._create(er.ScriptConditions.ScriptCondition.TerrainCondition.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `er.ScriptCondition.TerrainCondition`
   */
  public object TerrainConditionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: er.ScriptConditions.ScriptCondition.TerrainCondition.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: er.ScriptConditions.ScriptCondition.TerrainCondition.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): er.ScriptConditions.ScriptCondition.TerrainCondition = _builder.build()

      /**
       * `.er.Terrain terrain = 1;`
       */
      public var terrain: er.ScriptConditions.Terrain
        @JvmName("getTerrain")
        get() = _builder.terrain
        @JvmName("setTerrain")
        set(value) {
          _builder.terrain = value
        }
      public var terrainValue: kotlin.Int
        @JvmName("getTerrainValue")
        get() = _builder.terrainValue
        @JvmName("setTerrainValue")
        set(value) {
          _builder.terrainValue = value
        }
      /**
       * `.er.Terrain terrain = 1;`
       */
      public fun clearTerrain() {
        _builder.clearTerrain()
      }

      /**
       * `.er.Battler battler = 2;`
       */
      public var battler: er.ScriptConditions.Battler
        @JvmName("getBattler")
        get() = _builder.battler
        @JvmName("setBattler")
        set(value) {
          _builder.battler = value
        }
      public var battlerValue: kotlin.Int
        @JvmName("getBattlerValue")
        get() = _builder.battlerValue
        @JvmName("setBattlerValue")
        set(value) {
          _builder.battlerValue = value
        }
      /**
       * `.er.Battler battler = 2;`
       */
      public fun clearBattler() {
        _builder.clearBattler()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializefieldEffectCondition")
  public inline fun fieldEffectCondition(block: er.ScriptConditionKt.FieldEffectConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.FieldEffectCondition =
    er.ScriptConditionKt.FieldEffectConditionKt.Dsl._create(er.ScriptConditions.ScriptCondition.FieldEffectCondition.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `er.ScriptCondition.FieldEffectCondition`
   */
  public object FieldEffectConditionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: er.ScriptConditions.ScriptCondition.FieldEffectCondition.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: er.ScriptConditions.ScriptCondition.FieldEffectCondition.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): er.ScriptConditions.ScriptCondition.FieldEffectCondition = _builder.build()

      /**
       * `.er.FieldEffect effect = 1;`
       */
      public var effect: er.ScriptConditions.FieldEffect
        @JvmName("getEffect")
        get() = _builder.effect
        @JvmName("setEffect")
        set(value) {
          _builder.effect = value
        }
      public var effectValue: kotlin.Int
        @JvmName("getEffectValue")
        get() = _builder.effectValue
        @JvmName("setEffectValue")
        set(value) {
          _builder.effectValue = value
        }
      /**
       * `.er.FieldEffect effect = 1;`
       */
      public fun clearEffect() {
        _builder.clearEffect()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializeabilityCondition")
  public inline fun abilityCondition(block: er.ScriptConditionKt.AbilityConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.AbilityCondition =
    er.ScriptConditionKt.AbilityConditionKt.Dsl._create(er.ScriptConditions.ScriptCondition.AbilityCondition.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `er.ScriptCondition.AbilityCondition`
   */
  public object AbilityConditionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: er.ScriptConditions.ScriptCondition.AbilityCondition.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: er.ScriptConditions.ScriptCondition.AbilityCondition.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): er.ScriptConditions.ScriptCondition.AbilityCondition = _builder.build()

      /**
       * `.er.AbilityEnum ability = 1;`
       */
      public var ability: er.proto.AbilityEnum
        @JvmName("getAbility")
        get() = _builder.ability
        @JvmName("setAbility")
        set(value) {
          _builder.ability = value
        }
      public var abilityValue: kotlin.Int
        @JvmName("getAbilityValue")
        get() = _builder.abilityValue
        @JvmName("setAbilityValue")
        set(value) {
          _builder.abilityValue = value
        }
      /**
       * `.er.AbilityEnum ability = 1;`
       */
      public fun clearAbility() {
        _builder.clearAbility()
      }

      /**
       * `.er.Battler battler = 2;`
       */
      public var battler: er.ScriptConditions.Battler
        @JvmName("getBattler")
        get() = _builder.battler
        @JvmName("setBattler")
        set(value) {
          _builder.battler = value
        }
      public var battlerValue: kotlin.Int
        @JvmName("getBattlerValue")
        get() = _builder.battlerValue
        @JvmName("setBattlerValue")
        set(value) {
          _builder.battlerValue = value
        }
      /**
       * `.er.Battler battler = 2;`
       */
      public fun clearBattler() {
        _builder.clearBattler()
      }

      /**
       * `bool check_mold_breaker = 3;`
       */
      public var checkMoldBreaker: kotlin.Boolean
        @JvmName("getCheckMoldBreaker")
        get() = _builder.checkMoldBreaker
        @JvmName("setCheckMoldBreaker")
        set(value) {
          _builder.checkMoldBreaker = value
        }
      /**
       * `bool check_mold_breaker = 3;`
       */
      public fun clearCheckMoldBreaker() {
        _builder.clearCheckMoldBreaker()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializehp")
  public inline fun hp(block: er.ScriptConditionKt.HpKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.Hp =
    er.ScriptConditionKt.HpKt.Dsl._create(er.ScriptConditions.ScriptCondition.Hp.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `er.ScriptCondition.Hp`
   */
  public object HpKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: er.ScriptConditions.ScriptCondition.Hp.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: er.ScriptConditions.ScriptCondition.Hp.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): er.ScriptConditions.ScriptCondition.Hp = _builder.build()

      /**
       * `.er.ScriptCondition.Hp.HpType hp = 1;`
       */
      public var hp: er.ScriptConditions.ScriptCondition.Hp.HpType
        @JvmName("getHp")
        get() = _builder.hp
        @JvmName("setHp")
        set(value) {
          _builder.hp = value
        }
      public var hpValue: kotlin.Int
        @JvmName("getHpValue")
        get() = _builder.hpValue
        @JvmName("setHpValue")
        set(value) {
          _builder.hpValue = value
        }
      /**
       * `.er.ScriptCondition.Hp.HpType hp = 1;`
       */
      public fun clearHp() {
        _builder.clearHp()
      }

      /**
       * `.er.Battler battler = 2;`
       */
      public var battler: er.ScriptConditions.Battler
        @JvmName("getBattler")
        get() = _builder.battler
        @JvmName("setBattler")
        set(value) {
          _builder.battler = value
        }
      public var battlerValue: kotlin.Int
        @JvmName("getBattlerValue")
        get() = _builder.battlerValue
        @JvmName("setBattlerValue")
        set(value) {
          _builder.battlerValue = value
        }
      /**
       * `.er.Battler battler = 2;`
       */
      public fun clearBattler() {
        _builder.clearBattler()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializerecentFainted")
  public inline fun recentFainted(block: er.ScriptConditionKt.RecentFaintedKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.RecentFainted =
    er.ScriptConditionKt.RecentFaintedKt.Dsl._create(er.ScriptConditions.ScriptCondition.RecentFainted.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `er.ScriptCondition.RecentFainted`
   */
  public object RecentFaintedKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: er.ScriptConditions.ScriptCondition.RecentFainted.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: er.ScriptConditions.ScriptCondition.RecentFainted.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): er.ScriptConditions.ScriptCondition.RecentFainted = _builder.build()

      /**
       * `.er.Battler battler = 1;`
       */
      public var battler: er.ScriptConditions.Battler
        @JvmName("getBattler")
        get() = _builder.battler
        @JvmName("setBattler")
        set(value) {
          _builder.battler = value
        }
      public var battlerValue: kotlin.Int
        @JvmName("getBattlerValue")
        get() = _builder.battlerValue
        @JvmName("setBattlerValue")
        set(value) {
          _builder.battlerValue = value
        }
      /**
       * `.er.Battler battler = 1;`
       */
      public fun clearBattler() {
        _builder.clearBattler()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializespeciesCondition")
  public inline fun speciesCondition(block: er.ScriptConditionKt.SpeciesConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.SpeciesCondition =
    er.ScriptConditionKt.SpeciesConditionKt.Dsl._create(er.ScriptConditions.ScriptCondition.SpeciesCondition.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `er.ScriptCondition.SpeciesCondition`
   */
  public object SpeciesConditionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: er.ScriptConditions.ScriptCondition.SpeciesCondition.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: er.ScriptConditions.ScriptCondition.SpeciesCondition.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): er.ScriptConditions.ScriptCondition.SpeciesCondition = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class SpeciesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `repeated .er.SpeciesEnum species = 1;`
       */
      public val species: com.google.protobuf.kotlin.DslList<er.proto.SpeciesEnum, SpeciesProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.speciesList
        )
      /**
       * `repeated .er.SpeciesEnum species = 1;`
       * @param value The species to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addSpecies")
      public fun com.google.protobuf.kotlin.DslList<er.proto.SpeciesEnum, SpeciesProxy>.add(value: er.proto.SpeciesEnum) {
        _builder.addSpecies(value)
      }/**
       * `repeated .er.SpeciesEnum species = 1;`
       * @param value The species to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignSpecies")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<er.proto.SpeciesEnum, SpeciesProxy>.plusAssign(value: er.proto.SpeciesEnum) {
        add(value)
      }/**
       * `repeated .er.SpeciesEnum species = 1;`
       * @param values The species to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllSpecies")
      public fun com.google.protobuf.kotlin.DslList<er.proto.SpeciesEnum, SpeciesProxy>.addAll(values: kotlin.collections.Iterable<er.proto.SpeciesEnum>) {
        _builder.addAllSpecies(values)
      }/**
       * `repeated .er.SpeciesEnum species = 1;`
       * @param values The species to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllSpecies")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<er.proto.SpeciesEnum, SpeciesProxy>.plusAssign(values: kotlin.collections.Iterable<er.proto.SpeciesEnum>) {
        addAll(values)
      }/**
       * `repeated .er.SpeciesEnum species = 1;`
       * @param index The index to set the value at.
       * @param value The species to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setSpecies")
      public operator fun com.google.protobuf.kotlin.DslList<er.proto.SpeciesEnum, SpeciesProxy>.set(index: kotlin.Int, value: er.proto.SpeciesEnum) {
        _builder.setSpecies(index, value)
      }/**
       * `repeated .er.SpeciesEnum species = 1;`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearSpecies")
      public fun com.google.protobuf.kotlin.DslList<er.proto.SpeciesEnum, SpeciesProxy>.clear() {
        _builder.clearSpecies()
      }
      /**
       * `.er.Battler battler = 2;`
       */
      public var battler: er.ScriptConditions.Battler
        @JvmName("getBattler")
        get() = _builder.battler
        @JvmName("setBattler")
        set(value) {
          _builder.battler = value
        }
      public var battlerValue: kotlin.Int
        @JvmName("getBattlerValue")
        get() = _builder.battlerValue
        @JvmName("setBattlerValue")
        set(value) {
          _builder.battlerValue = value
        }
      /**
       * `.er.Battler battler = 2;`
       */
      public fun clearBattler() {
        _builder.clearBattler()
      }

      /**
       * `bool exact = 3;`
       */
      public var exact: kotlin.Boolean
        @JvmName("getExact")
        get() = _builder.exact
        @JvmName("setExact")
        set(value) {
          _builder.exact = value
        }
      /**
       * `bool exact = 3;`
       */
      public fun clearExact() {
        _builder.clearExact()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializeitemCondition")
  public inline fun itemCondition(block: er.ScriptConditionKt.ItemConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.ItemCondition =
    er.ScriptConditionKt.ItemConditionKt.Dsl._create(er.ScriptConditions.ScriptCondition.ItemCondition.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `er.ScriptCondition.ItemCondition`
   */
  public object ItemConditionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: er.ScriptConditions.ScriptCondition.ItemCondition.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: er.ScriptConditions.ScriptCondition.ItemCondition.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): er.ScriptConditions.ScriptCondition.ItemCondition = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class ItemProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `repeated .er.ItemEnum item = 1;`
       */
      public val item: com.google.protobuf.kotlin.DslList<er.proto.ItemEnum, ItemProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.itemList
        )
      /**
       * `repeated .er.ItemEnum item = 1;`
       * @param value The item to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addItem")
      public fun com.google.protobuf.kotlin.DslList<er.proto.ItemEnum, ItemProxy>.add(value: er.proto.ItemEnum) {
        _builder.addItem(value)
      }/**
       * `repeated .er.ItemEnum item = 1;`
       * @param value The item to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignItem")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<er.proto.ItemEnum, ItemProxy>.plusAssign(value: er.proto.ItemEnum) {
        add(value)
      }/**
       * `repeated .er.ItemEnum item = 1;`
       * @param values The item to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllItem")
      public fun com.google.protobuf.kotlin.DslList<er.proto.ItemEnum, ItemProxy>.addAll(values: kotlin.collections.Iterable<er.proto.ItemEnum>) {
        _builder.addAllItem(values)
      }/**
       * `repeated .er.ItemEnum item = 1;`
       * @param values The item to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllItem")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<er.proto.ItemEnum, ItemProxy>.plusAssign(values: kotlin.collections.Iterable<er.proto.ItemEnum>) {
        addAll(values)
      }/**
       * `repeated .er.ItemEnum item = 1;`
       * @param index The index to set the value at.
       * @param value The item to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setItem")
      public operator fun com.google.protobuf.kotlin.DslList<er.proto.ItemEnum, ItemProxy>.set(index: kotlin.Int, value: er.proto.ItemEnum) {
        _builder.setItem(index, value)
      }/**
       * `repeated .er.ItemEnum item = 1;`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearItem")
      public fun com.google.protobuf.kotlin.DslList<er.proto.ItemEnum, ItemProxy>.clear() {
        _builder.clearItem()
      }
      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class HoldEffectProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * `repeated .er.HoldEffect hold_effect = 2;`
       */
      public val holdEffect: com.google.protobuf.kotlin.DslList<er.proto.HoldEffect, HoldEffectProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.holdEffectList
        )
      /**
       * `repeated .er.HoldEffect hold_effect = 2;`
       * @param value The holdEffect to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addHoldEffect")
      public fun com.google.protobuf.kotlin.DslList<er.proto.HoldEffect, HoldEffectProxy>.add(value: er.proto.HoldEffect) {
        _builder.addHoldEffect(value)
      }/**
       * `repeated .er.HoldEffect hold_effect = 2;`
       * @param value The holdEffect to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignHoldEffect")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<er.proto.HoldEffect, HoldEffectProxy>.plusAssign(value: er.proto.HoldEffect) {
        add(value)
      }/**
       * `repeated .er.HoldEffect hold_effect = 2;`
       * @param values The holdEffect to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllHoldEffect")
      public fun com.google.protobuf.kotlin.DslList<er.proto.HoldEffect, HoldEffectProxy>.addAll(values: kotlin.collections.Iterable<er.proto.HoldEffect>) {
        _builder.addAllHoldEffect(values)
      }/**
       * `repeated .er.HoldEffect hold_effect = 2;`
       * @param values The holdEffect to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllHoldEffect")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<er.proto.HoldEffect, HoldEffectProxy>.plusAssign(values: kotlin.collections.Iterable<er.proto.HoldEffect>) {
        addAll(values)
      }/**
       * `repeated .er.HoldEffect hold_effect = 2;`
       * @param index The index to set the value at.
       * @param value The holdEffect to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setHoldEffect")
      public operator fun com.google.protobuf.kotlin.DslList<er.proto.HoldEffect, HoldEffectProxy>.set(index: kotlin.Int, value: er.proto.HoldEffect) {
        _builder.setHoldEffect(index, value)
      }/**
       * `repeated .er.HoldEffect hold_effect = 2;`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearHoldEffect")
      public fun com.google.protobuf.kotlin.DslList<er.proto.HoldEffect, HoldEffectProxy>.clear() {
        _builder.clearHoldEffect()
      }
      /**
       * `.er.Battler battler = 3;`
       */
      public var battler: er.ScriptConditions.Battler
        @JvmName("getBattler")
        get() = _builder.battler
        @JvmName("setBattler")
        set(value) {
          _builder.battler = value
        }
      public var battlerValue: kotlin.Int
        @JvmName("getBattlerValue")
        get() = _builder.battlerValue
        @JvmName("setBattlerValue")
        set(value) {
          _builder.battlerValue = value
        }
      /**
       * `.er.Battler battler = 3;`
       */
      public fun clearBattler() {
        _builder.clearBattler()
      }

      /**
       * `bool skip_disabling = 4;`
       */
      public var skipDisabling: kotlin.Boolean
        @JvmName("getSkipDisabling")
        get() = _builder.skipDisabling
        @JvmName("setSkipDisabling")
        set(value) {
          _builder.skipDisabling = value
        }
      /**
       * `bool skip_disabling = 4;`
       */
      public fun clearSkipDisabling() {
        _builder.clearSkipDisabling()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.copy(block: `er`.ScriptConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition =
  `er`.ScriptConditionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.WeatherCondition.copy(block: `er`.ScriptConditionKt.WeatherConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.WeatherCondition =
  `er`.ScriptConditionKt.WeatherConditionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.Damaged.copy(block: `er`.ScriptConditionKt.DamagedKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.Damaged =
  `er`.ScriptConditionKt.DamagedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.StatusCondition.copy(block: `er`.ScriptConditionKt.StatusConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.StatusCondition =
  `er`.ScriptConditionKt.StatusConditionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.Switching.copy(block: `er`.ScriptConditionKt.SwitchingKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.Switching =
  `er`.ScriptConditionKt.SwitchingKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.ActsAfter.copy(block: `er`.ScriptConditionKt.ActsAfterKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.ActsAfter =
  `er`.ScriptConditionKt.ActsAfterKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.TerrainCondition.copy(block: `er`.ScriptConditionKt.TerrainConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.TerrainCondition =
  `er`.ScriptConditionKt.TerrainConditionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.FieldEffectCondition.copy(block: `er`.ScriptConditionKt.FieldEffectConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.FieldEffectCondition =
  `er`.ScriptConditionKt.FieldEffectConditionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.AbilityCondition.copy(block: `er`.ScriptConditionKt.AbilityConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.AbilityCondition =
  `er`.ScriptConditionKt.AbilityConditionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.Hp.copy(block: `er`.ScriptConditionKt.HpKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.Hp =
  `er`.ScriptConditionKt.HpKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.RecentFainted.copy(block: `er`.ScriptConditionKt.RecentFaintedKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.RecentFainted =
  `er`.ScriptConditionKt.RecentFaintedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.SpeciesCondition.copy(block: `er`.ScriptConditionKt.SpeciesConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.SpeciesCondition =
  `er`.ScriptConditionKt.SpeciesConditionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun er.ScriptConditions.ScriptCondition.ItemCondition.copy(block: `er`.ScriptConditionKt.ItemConditionKt.Dsl.() -> kotlin.Unit): er.ScriptConditions.ScriptCondition.ItemCondition =
  `er`.ScriptConditionKt.ItemConditionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val er.ScriptConditions.ScriptConditionOrBuilder.weatherOrNull: er.ScriptConditions.ScriptCondition.WeatherCondition?
  get() = if (hasWeather()) getWeather() else null

public val er.ScriptConditions.ScriptConditionOrBuilder.damagedOrNull: er.ScriptConditions.ScriptCondition.Damaged?
  get() = if (hasDamaged()) getDamaged() else null

public val er.ScriptConditions.ScriptConditionOrBuilder.statusOrNull: er.ScriptConditions.ScriptCondition.StatusCondition?
  get() = if (hasStatus()) getStatus() else null

public val er.ScriptConditions.ScriptConditionOrBuilder.switchingOrNull: er.ScriptConditions.ScriptCondition.Switching?
  get() = if (hasSwitching()) getSwitching() else null

public val er.ScriptConditions.ScriptConditionOrBuilder.actsAfterOrNull: er.ScriptConditions.ScriptCondition.ActsAfter?
  get() = if (hasActsAfter()) getActsAfter() else null

public val er.ScriptConditions.ScriptConditionOrBuilder.terrainOrNull: er.ScriptConditions.ScriptCondition.TerrainCondition?
  get() = if (hasTerrain()) getTerrain() else null

public val er.ScriptConditions.ScriptConditionOrBuilder.fieldEffectOrNull: er.ScriptConditions.ScriptCondition.FieldEffectCondition?
  get() = if (hasFieldEffect()) getFieldEffect() else null

public val er.ScriptConditions.ScriptConditionOrBuilder.abilityOrNull: er.ScriptConditions.ScriptCondition.AbilityCondition?
  get() = if (hasAbility()) getAbility() else null

public val er.ScriptConditions.ScriptConditionOrBuilder.hpOrNull: er.ScriptConditions.ScriptCondition.Hp?
  get() = if (hasHp()) getHp() else null

public val er.ScriptConditions.ScriptConditionOrBuilder.recentFaintedOrNull: er.ScriptConditions.ScriptCondition.RecentFainted?
  get() = if (hasRecentFainted()) getRecentFainted() else null

public val er.ScriptConditions.ScriptConditionOrBuilder.speciesOrNull: er.ScriptConditions.ScriptCondition.SpeciesCondition?
  get() = if (hasSpecies()) getSpecies() else null

public val er.ScriptConditions.ScriptConditionOrBuilder.itemOrNull: er.ScriptConditions.ScriptCondition.ItemCondition?
  get() = if (hasItem()) getItem() else null

