#ifndef GUARD_TMHM_STRUCT_H
#define GUARD_TMHM_STRUCT_H

#include "global.h"
#include "constants/moves.h"

#define ALL_TMS \
TM_DECORATOR(MOVE_NONE)

#define TM_ENUM(tm) TM_ENUM_##tm
#define TM_DECORATOR(tm) TM_ENUM(tm),

typedef enum
{
    ALL_TMS
    TM_COUNT
} TmHmEnum;

#undef TM_DECORATOR

#define TM_BIT_FIELD(tm) TM_FIELD_##tm
#define TM_DECORATOR(tm) bool8 TM_BIT_FIELD(tm):1;

struct TmHmStruct
{
    ALL_TMS
};

union TmHmUnion
{
    u32 bits[(TM_COUNT + 31) / 32];
    struct TmHmStruct fields;
};

#undef TM_DECORATOR

extern const u16 gTmMoveMapping[];

#define ALL_TUTORS \
/* Primary attacks */ \
TUTOR_DECORATOR(MOVE_ABSORB) \
TUTOR_DECORATOR(MOVE_ACROBATICS) \
TUTOR_DECORATOR(MOVE_AIR_SLASH) \
TUTOR_DECORATOR(MOVE_AQUA_TAIL) \
TUTOR_DECORATOR(MOVE_AURA_SPHERE) \
TUTOR_DECORATOR(MOVE_BLACK_MAGIC) \
TUTOR_DECORATOR(MOVE_BLIZZARD) \
TUTOR_DECORATOR(MOVE_BODY_PRESS) \
TUTOR_DECORATOR(MOVE_BRAVADO) \
TUTOR_DECORATOR(MOVE_BUG_BUZZ) \
TUTOR_DECORATOR(MOVE_CRUSH_CLAW) \
TUTOR_DECORATOR(MOVE_CUT) \
TUTOR_DECORATOR(MOVE_DARK_PULSE) \
TUTOR_DECORATOR(MOVE_DAZZLING_GLEAM) \
TUTOR_DECORATOR(MOVE_DIG) \
TUTOR_DECORATOR(MOVE_DISCHARGE) \
TUTOR_DECORATOR(MOVE_DIVE) \
TUTOR_DECORATOR(MOVE_DOUBLE_LARIAT) \
TUTOR_DECORATOR(MOVE_DRAGON_CLAW) \
TUTOR_DECORATOR(MOVE_DRAGON_PULSE) \
TUTOR_DECORATOR(MOVE_DRAINING_KISS) \
TUTOR_DECORATOR(MOVE_DRILL_RUN) \
TUTOR_DECORATOR(MOVE_EARTHQUAKE) \
TUTOR_DECORATOR(MOVE_EARTH_POWER) \
TUTOR_DECORATOR(MOVE_EERIE_SPELL) \
TUTOR_DECORATOR(MOVE_ENERGY_BALL) \
TUTOR_DECORATOR(MOVE_ENERGY_WAVE) \
TUTOR_DECORATOR(MOVE_EXTRASENSORY) \
TUTOR_DECORATOR(MOVE_FACADE) \
TUTOR_DECORATOR(MOVE_FALSE_SWIPE) \
TUTOR_DECORATOR(MOVE_FEINT) \
TUTOR_DECORATOR(MOVE_FIRE_BLAST) \
TUTOR_DECORATOR(MOVE_FIRE_PUNCH) \
TUTOR_DECORATOR(MOVE_FLAMETHROWER) \
TUTOR_DECORATOR(MOVE_FLASH) \
TUTOR_DECORATOR(MOVE_FLASH_CANNON) \
TUTOR_DECORATOR(MOVE_FLY) \
TUTOR_DECORATOR(MOVE_FOCUS_BLAST) \
TUTOR_DECORATOR(MOVE_FOCUS_PUNCH) \
TUTOR_DECORATOR(MOVE_FORCE_PALM) \
TUTOR_DECORATOR(MOVE_FRUSTRATION) \
TUTOR_DECORATOR(MOVE_GIGA_IMPACT) \
TUTOR_DECORATOR(MOVE_GUNK_SHOT) \
TUTOR_DECORATOR(MOVE_HARD_PRESS) \
TUTOR_DECORATOR(MOVE_HEADBUTT) \
TUTOR_DECORATOR(MOVE_HEAT_CRASH) \
TUTOR_DECORATOR(MOVE_HEAT_WAVE) \
TUTOR_DECORATOR(MOVE_HEAVY_SLAM) \
TUTOR_DECORATOR(MOVE_HEX) \
TUTOR_DECORATOR(MOVE_HIDDEN_POWER) \
TUTOR_DECORATOR(MOVE_HORN_ATTACK) \
TUTOR_DECORATOR(MOVE_HYPER_BEAM) \
TUTOR_DECORATOR(MOVE_HYPER_VOICE) \
TUTOR_DECORATOR(MOVE_ICE_BEAM) \
TUTOR_DECORATOR(MOVE_ICE_PUNCH) \
TUTOR_DECORATOR(MOVE_IRON_FANGS) \
TUTOR_DECORATOR(MOVE_IRON_HEAD) \
TUTOR_DECORATOR(MOVE_KARATE_CHOP) \
TUTOR_DECORATOR(MOVE_LEECH_LIFE) \
TUTOR_DECORATOR(MOVE_LIQUIDATION) \
TUTOR_DECORATOR(MOVE_LOW_KICK) \
TUTOR_DECORATOR(MOVE_MACH_PUNCH) \
TUTOR_DECORATOR(MOVE_METAL_CLAW) \
TUTOR_DECORATOR(MOVE_NIGHT_SHADE) \
TUTOR_DECORATOR(MOVE_NIGHT_SLASH) \
TUTOR_DECORATOR(MOVE_PLAY_ROUGH) \
TUTOR_DECORATOR(MOVE_POISON_JAB) \
TUTOR_DECORATOR(MOVE_POWDER_SNOW) \
TUTOR_DECORATOR(MOVE_POWER_GEM) \
TUTOR_DECORATOR(MOVE_PSYCHIC) \
TUTOR_DECORATOR(MOVE_PSYCHIC_NOISE) \
TUTOR_DECORATOR(MOVE_PSYCHO_CUT) \
TUTOR_DECORATOR(MOVE_PSYSHOCK) \
TUTOR_DECORATOR(MOVE_RAZOR_LEAF) \
TUTOR_DECORATOR(MOVE_RETALIATE) \
TUTOR_DECORATOR(MOVE_RETURN) \
TUTOR_DECORATOR(MOVE_ROCK_SLIDE) \
TUTOR_DECORATOR(MOVE_ROCK_THROW) \
TUTOR_DECORATOR(MOVE_ROCK_TOMB) \
TUTOR_DECORATOR(MOVE_SECRET_POWER) \
TUTOR_DECORATOR(MOVE_SEED_BOMB) \
TUTOR_DECORATOR(MOVE_SEISMIC_TOSS) \
TUTOR_DECORATOR(MOVE_SHADOW_BALL) \
TUTOR_DECORATOR(MOVE_SHADOW_CLAW) \
TUTOR_DECORATOR(MOVE_SKY_DROP) \
TUTOR_DECORATOR(MOVE_SLUDGE_BOMB) \
TUTOR_DECORATOR(MOVE_SOLAR_BEAM) \
TUTOR_DECORATOR(MOVE_STONE_EDGE) \
TUTOR_DECORATOR(MOVE_SURF) \
TUTOR_DECORATOR(MOVE_TAKE_DOWN) \
TUTOR_DECORATOR(MOVE_TECTONIC_FANGS) \
TUTOR_DECORATOR(MOVE_THUNDER) \
TUTOR_DECORATOR(MOVE_THUNDERBOLT) \
TUTOR_DECORATOR(MOVE_THUNDER_PUNCH) \
TUTOR_DECORATOR(MOVE_WATER_PULSE) \
TUTOR_DECORATOR(MOVE_WEATHER_BALL) \
TUTOR_DECORATOR(MOVE_WILD_CHARGE) \
TUTOR_DECORATOR(MOVE_WING_ATTACK) \
TUTOR_DECORATOR(MOVE_X_SCISSOR) \
TUTOR_DECORATOR(MOVE_ZEN_HEADBUTT) \
/* Utility attacks */ \
TUTOR_DECORATOR(MOVE_AURORA_BEAM) \
TUTOR_DECORATOR(MOVE_BREAKING_SWIPE) \
TUTOR_DECORATOR(MOVE_BUBBLE) \
TUTOR_DECORATOR(MOVE_BUG_BITE) \
TUTOR_DECORATOR(MOVE_BULLDOZE) \
TUTOR_DECORATOR(MOVE_CHARGE_BEAM) \
TUTOR_DECORATOR(MOVE_CIRCLE_THROW) \
TUTOR_DECORATOR(MOVE_CLEAR_SMOG) \
TUTOR_DECORATOR(MOVE_COUNTER) \
TUTOR_DECORATOR(MOVE_COVET) \
TUTOR_DECORATOR(MOVE_DRAGON_TAIL) \
TUTOR_DECORATOR(MOVE_ELECTROWEB) \
TUTOR_DECORATOR(MOVE_FIRE_SPIN) \
TUTOR_DECORATOR(MOVE_FLAME_CHARGE) \
TUTOR_DECORATOR(MOVE_FLIP_TURN) \
TUTOR_DECORATOR(MOVE_FLUTTERING_LEAF) \
TUTOR_DECORATOR(MOVE_FOUL_PLAY) \
TUTOR_DECORATOR(MOVE_ICY_WIND) \
TUTOR_DECORATOR(MOVE_KNOCK_OFF) \
TUTOR_DECORATOR(MOVE_LEAF_TORNADO) \
TUTOR_DECORATOR(MOVE_LICK) \
TUTOR_DECORATOR(MOVE_MIRROR_COAT) \
TUTOR_DECORATOR(MOVE_MIRROR_SHOT) \
TUTOR_DECORATOR(MOVE_PLUCK) \
TUTOR_DECORATOR(MOVE_POISON_TAIL) \
TUTOR_DECORATOR(MOVE_POWER_UP_PUNCH) \
TUTOR_DECORATOR(MOVE_PSYBEAM) \
TUTOR_DECORATOR(MOVE_PURSUIT) \
TUTOR_DECORATOR(MOVE_RAPID_SPIN) \
TUTOR_DECORATOR(MOVE_SAND_TOMB) \
TUTOR_DECORATOR(MOVE_THIEF) \
TUTOR_DECORATOR(MOVE_U_TURN) \
TUTOR_DECORATOR(MOVE_VOLT_SWITCH) \
TUTOR_DECORATOR(MOVE_WHIRLPOOL) \
TUTOR_DECORATOR(MOVE_WHIRLWIND) \
/* Strong status */ \
TUTOR_DECORATOR(MOVE_ACID_ARMOR) \
TUTOR_DECORATOR(MOVE_AGILITY) \
TUTOR_DECORATOR(MOVE_AROMATHERAPY) \
TUTOR_DECORATOR(MOVE_BLOOD_SHOT) \
TUTOR_DECORATOR(MOVE_BULK_UP) \
TUTOR_DECORATOR(MOVE_CALM_MIND) \
TUTOR_DECORATOR(MOVE_CONFUSE_RAY) \
TUTOR_DECORATOR(MOVE_CORROSIVE_GAS) \
TUTOR_DECORATOR(MOVE_CREEPING_THORNS) \
TUTOR_DECORATOR(MOVE_CURSE) \
TUTOR_DECORATOR(MOVE_DEFOG) \
TUTOR_DECORATOR(MOVE_FLASH_FREEZE) \
TUTOR_DECORATOR(MOVE_FLORAL_HEALING) \
TUTOR_DECORATOR(MOVE_HAZE) \
TUTOR_DECORATOR(MOVE_IRON_DEFENSE) \
TUTOR_DECORATOR(MOVE_LEECH_SEED) \
TUTOR_DECORATOR(MOVE_LIFE_DEW) \
TUTOR_DECORATOR(MOVE_LIGHT_SCREEN) \
TUTOR_DECORATOR(MOVE_NASTY_PLOT) \
TUTOR_DECORATOR(MOVE_RAGE_POWDER) \
TUTOR_DECORATOR(MOVE_REFLECT) \
TUTOR_DECORATOR(MOVE_ROOST) \
TUTOR_DECORATOR(MOVE_SPIKES) \
TUTOR_DECORATOR(MOVE_STEALTH_ROCK) \
TUTOR_DECORATOR(MOVE_SUPERSONIC) \
TUTOR_DECORATOR(MOVE_SWEET_KISS) \
TUTOR_DECORATOR(MOVE_SWORDS_DANCE) \
TUTOR_DECORATOR(MOVE_TAILWIND) \
TUTOR_DECORATOR(MOVE_TAUNT) \
TUTOR_DECORATOR(MOVE_THUNDER_WAVE) \
TUTOR_DECORATOR(MOVE_TOXIC) \
TUTOR_DECORATOR(MOVE_TOXIC_SPIKES) \
TUTOR_DECORATOR(MOVE_TRICK) \
TUTOR_DECORATOR(MOVE_TRICK_ROOM) \
TUTOR_DECORATOR(MOVE_WILL_O_WISP) \
/* Niche status */ \
TUTOR_DECORATOR(MOVE_AQUA_RING) \
TUTOR_DECORATOR(MOVE_BABY_DOLL_EYES) \
TUTOR_DECORATOR(MOVE_CHARM) \
TUTOR_DECORATOR(MOVE_COPYCAT) \
TUTOR_DECORATOR(MOVE_COTTON_SPORE) \
TUTOR_DECORATOR(MOVE_DRAGON_CHEER) \
TUTOR_DECORATOR(MOVE_FORESIGHT) \
TUTOR_DECORATOR(MOVE_GASTRO_ACID) \
TUTOR_DECORATOR(MOVE_GRUDGE) \
TUTOR_DECORATOR(MOVE_HEAL_BLOCK) \
TUTOR_DECORATOR(MOVE_INGRAIN) \
TUTOR_DECORATOR(MOVE_LASER_FOCUS) \
TUTOR_DECORATOR(MOVE_MAGNET_RISE) \
TUTOR_DECORATOR(MOVE_METAL_SOUND) \
TUTOR_DECORATOR(MOVE_MIRACLE_EYE) \
TUTOR_DECORATOR(MOVE_MIST) \
TUTOR_DECORATOR(MOVE_REFRESH) \
TUTOR_DECORATOR(MOVE_ROTOTILLER) \
TUTOR_DECORATOR(MOVE_SAFEGUARD) \
TUTOR_DECORATOR(MOVE_SKILL_SWAP) \
TUTOR_DECORATOR(MOVE_SOAK) \
TUTOR_DECORATOR(MOVE_SPIDER_WEB) \
TUTOR_DECORATOR(MOVE_SPITE) \
TUTOR_DECORATOR(MOVE_SPOTLIGHT) \
TUTOR_DECORATOR(MOVE_STRING_SHOT) \
TUTOR_DECORATOR(MOVE_TEARFUL_LOOK) \
TUTOR_DECORATOR(MOVE_TOPSY_TURVY) \
TUTOR_DECORATOR(MOVE_TORMENT) \
TUTOR_DECORATOR(MOVE_VENOM_DRENCH) \
TUTOR_DECORATOR(MOVE_WIDE_GUARD) \
TUTOR_DECORATOR(MOVE_WORK_UP) \
TUTOR_DECORATOR(MOVE_WORRY_SEED) \
/* Universal */ \
TUTOR_DECORATOR(MOVE_ATTRACT) \
TUTOR_DECORATOR(MOVE_ENDURE) \
TUTOR_DECORATOR(MOVE_HELPING_HAND) \
TUTOR_DECORATOR(MOVE_PROTECT) \
TUTOR_DECORATOR(MOVE_REST) \
TUTOR_DECORATOR(MOVE_SLEEP_TALK) \
TUTOR_DECORATOR(MOVE_SUBSTITUTE) \
/* Terrain */ \
TUTOR_DECORATOR(MOVE_ELECTRIC_TERRAIN) \
TUTOR_DECORATOR(MOVE_GRASSY_TERRAIN) \
TUTOR_DECORATOR(MOVE_MISTY_TERRAIN) \
TUTOR_DECORATOR(MOVE_PSYCHIC_TERRAIN) \
/* Weather */ \
TUTOR_DECORATOR(MOVE_EERIE_FOG) \
TUTOR_DECORATOR(MOVE_HAIL) \
TUTOR_DECORATOR(MOVE_RAIN_DANCE) \
TUTOR_DECORATOR(MOVE_SANDSTORM) \
TUTOR_DECORATOR(MOVE_SUNNY_DAY)

#define TUTOR_ENUM(tutor) TUTOR_ENUM_##tutor
#define TUTOR_DECORATOR(tutor) TUTOR_ENUM(tutor),

typedef enum
{
    ALL_TUTORS
    TUTOR_COUNT
} TutorEnum;

#undef TUTOR_DECORATOR

#define TUTOR_BIT_FIELD(tutor) TUTOR_FIELD_##tutor
#define TUTOR_DECORATOR(tutor) bool8 TUTOR_BIT_FIELD(tutor):1;

struct TutorStruct
{
    ALL_TUTORS
};

union TutorUnion
{
    u32 bits[(TUTOR_COUNT + 31) / 32];
    struct TutorStruct fields;
};

#undef TUTOR_DECORATOR

extern const u16 gTutorMoveMapping[];

u16 GetTmMove(u8 tmId);
u16 GetTutorMove(u8 tutorId);

#endif